# Generated by Django 4.0.1 on 2022-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('NM', 'Never Married'), ('D', 'Divorced'), ('AD', 'Awaiting Divorce')], max_length=100)),
            ],
        ),
    ]
