# Generated by Django 4.0.1 on 2022-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerpreference', '0002_alter_preference_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='marital_status',
            field=models.CharField(choices=[('NM', 'Never Married'), ('D', 'Divorced'), ('AD', 'Awaiting Divorce')], max_length=100),
        ),
    ]
